### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by Shatur**
* I fixed comments in `folerid_generator` (was broken after `cargo fmt`). BTW, what is this example for?
* Enabled clippy checks on examples and fixed warnings.
* Implemented `Copy` on enums. Enum values that smaller then pointer are faster to pass by value.
* Upgraded to Rust 2021. The only thing that I had to change was modules inclusion.
* Use [home](https://docs.rs/home/0.5.3/home/index.html) crate (used even by Cargo!) instead of deprecated `std::env::home_dir()`.
* Hide extra `pub` functions.
* Fix markdown doc and enable `clippy::doc_markdown`.

### CODE REVIEW

**Comment by mentaljam** [comment]
> I fixed comments in `folerid_generator` (was broken after `cargo fmt`). BTW, what is this example for?

It's output is used in [src/windows.rs](https://github.com/mentaljam/standard_paths/blob/2200ad3422789c8f0fb39551d06081926b6d0683/src/windows.rs). I don't remember why I've decided to implement it as an example but not a build script.

**Review by mentaljam — APPROVED** [review]

**Comment by Shatur** [comment]
> It's output is used in [src/windows.rs](https://github.com/mentaljam/standard_paths/blob/2200ad3422789c8f0fb39551d06081926b6d0683/src/windows.rs). I don't remember why I've decided to implement it as an example but not a build script.

Got it. Let's left it as is for now.

I planned some more changes, but I assume this can be merged as is if you agree on this PR.

**Comment by mentaljam** [comment]
I think you can continue committing to this PR. If you need take a break, I'll merge it and publish a release

**Comment by Shatur** [comment]
> I think you can continue committing to this PR.

Okay! I will continue today after work :)

**Comment by Shatur** [comment]
Done!

**Review by mentaljam — APPROVED** [review]

**Comment by Shatur** [comment]
@mentaljam I think I'm done, please merge and publish a release :)

**Comment by mentaljam** [comment]
Great! Thank you again!

**Pull request merged**
